name: Semantic Versioning

on:
  push:
    branches:
      - main  

jobs:
  semantic_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Semantic Versioning
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          change_path: "src/"
          namespace: todoapp
          bump_each_commit: false
          enable_prerelease_mode: true
          debug: false
          version_from_branch: false

